### ISSUE TITLE
Issue with preserve original breaks

### ISSUE THREAD

**Issue by krokyk** [Trivadis/plsql-formatter-settings#16] opened 2020-07-30 14:12 UTC
Consider this ugly piece of code:
```sql
SET ECHO OFF
BEGIN
    println('Creating general_tools package');
END;
/

----------------------------------------------------------------------------
-- begin package specification
----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE general_tools AS
FUNCTION exist_table (
usrname  VARCHAR2,
tabname  VARCHAR2
) RETURN BOOLEAN;
FUNCTION exist_column (
usrname  VARCHAR2,
tabname  VARCHAR2,
colname  VARCHAR2
) RETURN BOOLEAN;
END;
/
```
After formatting (settings are indent=4 and double break after statements, everything else default):
```sql
SET ECHO OFF

BEGIN
    println('Creating general_tools package');
END;
/

----------------------------------------------------------------------------
-- begin package specification
----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE general_tools AS

    FUNCTION exist_table (
        usrname  VARCHAR2,
        tabname  VARCHAR2
    ) RETURN BOOLEAN;

    FUNCTION exist_column (
        usrname  VARCHAR2,
        tabname  VARCHAR2,
        colname  VARCHAR2
    ) RETURN BOOLEAN;

END;
/
```

Everything looks great but let's say I don't like that empty line after the 1st line, empty line after the package declaration (after AS) and another empty line just before the last END;
So I decide to remove them like this:
```sql
SET ECHO OFF
BEGIN
    println('Creating general_tools package');
END;
/

----------------------------------------------------------------------------
-- begin package specification
----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE general_tools AS
    FUNCTION exist_table (
        usrname  VARCHAR2,
        tabname  VARCHAR2
    ) RETURN BOOLEAN;

    FUNCTION exist_column (
        usrname  VARCHAR2,
        tabname  VARCHAR2,
        colname  VARCHAR2
    ) RETURN BOOLEAN;
END;
/
```

Now I change the break settings to "Preserve original" and hit CTRL+F7 and see how the FUNCTIONs are misaligned
```sql
SET ECHO OFF
BEGIN
    println('Creating general_tools package');
END;
/

----------------------------------------------------------------------------
-- begin package specification
----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE general_tools AS
        FUNCTION exist_table (
        usrname  VARCHAR2,
        tabname  VARCHAR2
    ) RETURN BOOLEAN;

        FUNCTION exist_column (
        usrname  VARCHAR2,
        tabname  VARCHAR2,
        colname  VARCHAR2
    ) RETURN BOOLEAN;
END;
/
```

Line breaks were preserved, allright but that misalignment is a problem. Is that easy to fix?

**Comment by PhilippSalvisberg** [comment] 2020-07-30 16:37
This is similar to #10. The problem is that the code outside of Arbori is buggy in SQLDev 20.2. Using other values that "Single Break" lead already to wrong results in SQLDev 19.4 (See #2). At least "Double Break" works now. However, I expect this to be fixed with SQLDev 20.3. 

> Is that easy to fix?

No.  But it is possible. You have to identify all nodes where the indentation will be wrong with "Preserve Original" and remove all leading Spaces and Tabs (but keep the existing new lines). See also [this workaround](https://github.com/Trivadis/plsql-formatter-settings/blob/9926f7170a15adeb86f54ba7d501f60d3d6601a4/settings/sql_developer/trivadis_custom_format.arbori#L25-L89).

I keep this issue open and will check if it is solved with one of the next versions of SQLDev. In the meantime I suggest not to use "Preserve Original".

**Comment by PhilippSalvisberg** [comment] 2020-07-30 16:55
related to #6

**Closed** 2020-07-31 03:28 UTC
Labels: enhancement, needs new product version

**Comment by PhilippSalvisberg** [comment] 2020-07-31 03:32
This is the result with the latest settings (plus 4 spaces and "Preserve Original"):

```
SET ECHO OFF
BEGIN
    println('Creating general_tools package');
END;
/

----------------------------------------------------------------------------
-- begin package specification
----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE general_tools AS
    FUNCTION exist_table (
        usrname  VARCHAR2,
        tabname  VARCHAR2
    ) RETURN BOOLEAN;

    FUNCTION exist_column (
        usrname  VARCHAR2,
        tabname  VARCHAR2,
        colname  VARCHAR2
    ) RETURN BOOLEAN;
END;
/
```
